<?php

/**
 * @file
 * Used to handle custom migration functionalities.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cambridge_migrations_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cambridge_migrations':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 10 custom migration functionalities to process data from the cambridge drupal 7 websites.') . '</p>';
      return $output;
  }
}
