<?php

use Drupal\Core\Form\FormStateInterface;

/**
* Implements hook_theme_suggestions_alter().
*/
function cam_admin_ui_tweaks_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  switch ($hook) {
    case 'paragraph':
      $suggestions[] = $hook . '__' . 'admin_' . $variables['elements']['#view_mode'];
    break;
  }
}

function cam_admin_ui_tweaks_page_attachments(array &$attachments) {
  // Return Message Banner styling for all users.
  $attachments['#attached']['library'][] = 'cambridge_tailwind/message-banner-styling';

  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if ($is_admin) {
    $attachments['#attached']['library'][] = 'cam_admin_ui_tweaks/ckeditor';
    $attachments['#attached']['library'][] = 'cam_admin_ui_tweaks/paragraphs_ee';
    return;
  }
}

/**
* Implements hook_theme().
*/
function cam_admin_ui_tweaks_theme($existing, $type, $theme, $path) {
return [
  'paragraph__admin_preview' => [
  'base hook' => 'paragraph',
  'path' => $path . '/templates/paragraphs',
  ],
];
}

function cam_admin_ui_tweaks_preprocess_paragraph(&$variables) {
  $entity = $variables['paragraph'];
  $entity_type = $entity->getEntityTypeId();
  $entity_bundle = $entity->bundle();
  $bundle_info = \Drupal::service('entity_type.bundle.info')->getBundleInfo($entity_type);
  $variables['title'] = $bundle_info[$entity_bundle]['label'];
}

 /**
 * Implements hook_library_info_alter().
 */
function cam_admin_ui_tweaks_library_info_alter(array &$libraries, $extension)
{
  if ($extension === 'message_banner' && isset($libraries['message_banner'])) {
    $libraries['message_banner']['header'] = true;
  }
}

/**
 * Implements hook_field_widget_complete_form_alter().
 */
function cam_admin_ui_tweaks_field_widget_complete_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context) {
  // Check if the paragraphs widget exists and is enabled.
  if (isset($field_widget_complete_form['widget']['#paragraphs_widget']) && $field_widget_complete_form['widget']['#paragraphs_widget']) {
    
    // Loop through the widget array.
    foreach ($field_widget_complete_form['widget'] as &$widget) {
      // Make sure $widget is an array before using array access.
      if (is_array($widget) && isset($widget['top'])) {
        // Unset the icon from the 'type' within 'top' if it exists.
        if (isset($widget['top']['type']['icon'])) {
          unset($widget['top']['type']['icon']);
        }
      }
    }
  }
}
